bam_dir: /projects/BRANGWYNNE/projects/genomics/primary_data/2023/06_June/Nova-YCC-CutNRun/data/04_mapped_hg38
bam_filename_pattern: "2685__{sample}_S1_L001.aligned.hg38.mapq20.sorted.bam"

samples:
  - name: "y460-4"
    desc: "sgAlu"
  - name: "y460-5"
    desc: "sgNT"