# ========================
# Sample configurations
# ========================

# Directory containing the BAM files from the mapping step
bam_dir: /projects/BRANGWYNNE/projects/genomics/primary_data/2023/06_June/Nova-YCC-CutNRun/data/04_mapped_hg38

# Pattern of the BAM file names.
# - {sample} is a placeholder for the sample name
# - should be just the filename + extension, don't include the leading slash
bam_filename_pattern: "2685__{sample}_S1_L001.aligned.hg38.mapq20.sorted.bam"

# name is what can be inferred and parsed from file names
# desc is what is displayed in the legend
samples:
  - name: "y460-4"
    desc: "sgAlu"
  - name: "y460-5"
    desc: "sgNT"

# ========================
# Histogram configurations
# ========================
binwidth: 10
binrange: # min and max
  - 0
  - 1150
tick: 250
# See https://seaborn.pydata.org/generated/seaborn.objects.Hist.html
# for more options
stat: "proportion"

# Extra vertical lines
gatings:
  - 40
  - 120
  - 270
  - 440
  - 620