alu_families_fasta: /projects/BRANGWYNNE/users/yichec/resources/genomics/alu/dfam_alu.fa
rmsk: /projects/BRANGWYNNE/tools/genomics/rmsk/hg38.repeatmasker.bed
genome:
  hg38: /projects/BRANGWYNNE/tools/genomics/genomes/STAR/hg38/GRCh38.p13_STAR/chrNameLength.txt

# If truncation is set to 0, will use the full bedfile.
alu_annotation_truncation: 10000

bam_dir: /projects/BRANGWYNNE/projects/genomics/primary_data/2023/06_June/Nova-YCC-CutNRun/data/04_mapped_hg38
bam_filename_pattern: "/2685__{sample}_S1_L001.aligned.hg38.mapq20.sorted.bam"

samples:
  - name: "y460-4"
    desc: "sgAlu"
  - name: "y460-5"
    desc: "sgNT"

bam_to_bigwig:
  binsizes:
    - 10
    - 1

compute_matrix:
  cores: 1
  params:
    body: 300
    before: 50
    after: 50
