# Reference bedfile for alu annotations
# If truncation is set to 0, will use the full bedfile.
alu_annotation: 
  path: /projects/BRANGWYNNE/tools/genomics/rmsk/hg38.alu.repeats.sorted.bed
  truncation: 0

bam_dir: /projects/BRANGWYNNE/projects/genomics/primary_data/2023/06_June/Nova-YCC-CutNRun/data/05_mapped_hg38_nomapq
bam_filename_pattern: "/2685__{sample}_S1_L001.aligned.hg38.nomapq.sorted.bam"

samples:
  - name: "y460-4"
    desc: "sgAlu"
  - name: "y460-5"
    desc: "sgNT"

bam_to_bigwig:
  binsizes:
    - 10

compute_matrix:
  cores: 1
  params:
    before: 1000
    after: 1000