# ======================================================================
# Experiment-specific configurations
# ======================================================================

# No need to quote the strings in yaml files, but do so when special 
# characters are used. More importantly, even if they are quoted here,
# they still need to be quoted again when used in the "shell" derivative.
input:
  samplesheet_path: resources/example_data/samplesheet.csv
  image_path:
    dir: resources/example_data
    glob: '*002_Deno.nd2'
    regex: 'Well(?P<WellID>[A-H]\d{2})_\w+_fov(?P<FovID>\d{3})_snap-nodelay-snap002_Deno.nd2'
  datefmt: # leave blank if not used
  # channels has to be in the order as how they present in the raw file
  channels: 
    - oc: "640"
      fluoro: miRFP670
      colormap: magenta
      background: 100 
    - oc: "488"
      fluoro: sfGFP
      colormap: green
      background: 100
  bitdepth: 16